// The Google Apps Script Deployment ID provided by the user
export const GAS_DEPLOYMENT_ID = "AKfycbw-LWBmZo4KIFDc2W3sHAojHG6m16S5YbnIE6CfC9-cRPQ-3nGK11aD9i71wTr50kvybg";

export const API_URL = `https://script.google.com/macros/s/${GAS_DEPLOYMENT_ID}/exec`;

export const APP_NAME = "Kehadiran Pengawas PSS";
export const SCHOOL_NAME = "SK SATU SULTAN ALAM SHAH";

// Senarai Nama Induk (Master List)
export const STUDENT_MASTER_LIST = [
  "MUHAMMAD ISKANDAR RUZAINI BIN MOHAMAD AMZAR RUZAINI",
  "LAANA INARA AAISYA BT MOHD FATHUL HAZWAN",
  "AISYAH ZAHRA BINTI MUHAMMAD ZAID",
  "NUH AARIZ BIN NOR AHMADI",
  "YUSUF ILMAN BIN MOHD SAZUAN",
  "WAN NUR SAFFIYA HANNIN BINTI WAN MUHAMMAD SYAIFUL BAHAR",
  "NURQAISARAH HANINAH BINTI AHAMAD TARMIZI",
  "NUR HANEEM QAISARA BINTI MOHD.NORAZAM",
  "MUHAMMAD HUD IZZUDIN BIN MOHD KAMIL",
  "MUHAMMAD AFIQ BIN FAIRUZ AIZAM",
  "IZZAT IAN UMAR BIN MUHAMMAD IZZAT IZZUDDIN",
  "MUHAMMAD IZ'AAN BIN MOHAMAD YAMIN",
  "NURAISYAH NUHA DAYYINA BINTI MOHD YUSRI",
  "SITI NURAISY HAFIYA BINTI AZFAR",
  "UMAR HUZAYYFAH BIN AREZ",
  "ALANA SOPHIA BINTI ZULFADHLI",
  "AIMAN ASYRAF BIN MUHAMAD HAFIZ",
  "NUR ALANA SOFIA BINTI SHAHRUL",
  "KAISARA BINTI SHAMARUL IZWAN",
  "MUHAMMAD IMAN AQIL BIN AHMAD SYIHAN",
  "MUHAMMAD RAYYAN WAFI BIN MOHD NIZAM",
  "NYSSA NUHA BINTI MOHD RAZALI",
  "NUR QALESYA SOFEA BINTI MUHAMMAD AZRAR HAQKIMI",
  "SITI SYAMIM AMANI BINTI MD. ADNAN",
  "ALIF IRFAN BIN SAIFUL BOHARI",
  "IRSYAD IZZUDDIN BIN MOHD TARMEZEE"
];

export const TOTAL_STUDENTS = STUDENT_MASTER_LIST.length;